version: '3.8'
services:
  delaguia-cards:
    image: delaguia-cards:latest
    build:
      context: .
      args:
        VITE_BASE_URL: https://cards.delaguialuzon.es
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - proxy
networks:
  proxy:
    external: true