version: '3.8'
services:
  delaguia-cards:
    image: ghcr.io/delaguialuzon01/cards:latest
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - proxy
networks:
  proxy:
    external: true